### ISSUE TITLE
Cable TV Links not added

### ISSUE THREAD

**Issue by robyice** [piplongrun/arconaitv.bundle#2]
I noticed that none of Cable TV links was not added
so I adjusted the code to add this xpath before yours as this will return only the Live TV links
html.xpath('//*[@id="menu-item-832"]/ul')[0]

**Comment by piplongrun** [comment]
> I noticed that none of Cable TV links was not added

That's correct, I had some trouble getting the streams to work in some places. When this took more time than I hoped, I found that the quality of the streams is so extremely low, that I decided to not bother with them any longer :|
