### ISSUE TITLE
Stream keeps freezing

### ISSUE THREAD

**Issue by Tidyl** [piplongrun/arconaitv.bundle#3]
My streams keep stopping after about 30-60 minutes of playback. Interestingly enough most of the time the audio will continue for about 5-10 minutes before the entire stream just disconnects. Any ideas on what might be causing it?

**Comment by dougy27** [comment]
I think the problem is tied to deez nuts, please confirm?

**Comment by piplongrun** [comment]
I haven't got a clue, sorry, but this is not a channel issue. The channel just provides the player with a video url and that's it. If this is on specific Plex clients I suggest posting about the issue in the Plex forums in the correct category.

**Comment by Tidyl** [comment]
I think it might be related to how the stream url is grabbed. I'm guessing the HLS stream changes its urls on regular intervals, which is why the stream is freezing because it doesn't get the updated url.
